[package]
name = "cli-simple"
version = "0.1.0"
authors = ["Daniel Herkert <daniel.herkert@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hkp = { path = "../hkp" }
tokio = { version = "1.5", features = ["full"] }
dialoguer = "0.8.0"